apiVersion: v1
kind: Namespace
metadata:
  name: kuma-demo
  labels:
    kuma.io/sidecar-injection: enabled   # 指示 Kuma 服务网格在这个命名空间中自动注入 Sidecar 代理
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: kuma-demo
spec:
  selector:
    matchLabels:
      app: node-api
  replicas: 3
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: "node-api"
          imagePullPolicy: IfNotPresent   # 如果不存在本地镜像, 则从镜像仓库拉取          
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: POD_IP    # 设置 Pod IP 环境变量
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: node-api
  namespace: kuma-demo
  labels:
    app: node-api
spec:
  selector:
    app: node-api
  ports:
  - protocol: TCP
    appProtocol: http
    port: 3000
    nodePort: 30000
  type: NodePort